_wandb:
    value:
        cli_version: 0.22.2
        code_path: code/project/src/train_vae.py
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
            "3":
                - 15
                - 16
            "4": 3.13.2
            "5": 0.22.2
            "12": 0.22.2
            "13": darwin-arm64
batch_size:
    value: 128
beta_schedule:
    value: linear_warmup
checkpoint_dir:
    value: ../experiments/runs/55bdaf8f/checkpoints
class_weight_method:
    value: sqrt_inverse
class_weight_smooth:
    value: 1
data_path:
    value: ../datasets/test-100k/corpus.npz
device:
    value: cuda
early_stopping_min_delta:
    value: 0
early_stopping_patience:
    value: 3
focal_gamma:
    value: 2
gradient_clip_norm:
    value: 1
latent_dim:
    value: 32
learning_rate:
    value: 0.0005
log_every_n_steps:
    value: 10
lr_decay_epochs:
    value: 10
lr_decay_rate:
    value: 0.5
lr_min:
    value: 1e-05
lr_schedule_type:
    value: cosine
max_epochs:
    value: 5
min_kl_per_dim:
    value: 0.05
num_colors:
    value: 10
num_workers:
    value: 0
pin_memory:
    value: true
run_id:
    value: 55bdaf8f
runs_base_dir:
    value: ../experiments/runs
save_best_only:
    value: true
save_every_n_epochs:
    value: 1
seed:
    value: 42
target_pixel_accuracy:
    value: 0.9
use_augmentation:
    value: true
use_class_weights:
    value: true
use_focal_loss:
    value: true
use_lr_schedule:
    value: true
use_wandb:
    value: true
validate_every_n_epochs:
    value: 1
wandb_entity:
    value: null
wandb_project:
    value: arc-beta-vae
wandb_run_name:
    value: null
wandb_tags:
    value:
        - beta-vae
        - arc
        - experiment-0.2
